name: serial2mqtt
version: 1.1.6
slug: serial2mqtt
description: Serial to MQTT bridge
arch:
  - aarch64
uart: true
options:
  usb_port: "/dev/ttyUSB0"
  baud_rate: 115200
  mqtt_topic_prefix: "homeassistant/sensor"
schema:
  usb_port: device(subsystem=tty)
  baud_rate: int
  mqtt_topic_prefix: str
services:
  - mqtt:need
stage: experimental
init: false
